[tool.poetry]
name = "transmittance2fom-genmodels"
version = "0.1.0"
description = ""
authors = ["floriankark <florian.kark@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
